### ISSUE TITLE
Broken link to RUS emission data

### ISSUE THREAD

**Issue by Greenheart** [cheerfulstoic/kommun_compare#3]
http://extra.lansstyrelsen.se/rus/Sv/statistik-och-data/nationell-emissionsdatabas/Pages/default.aspx

**Comment by cheerfulstoic** [comment]
That seems to be the link that is already there... (???)

**Comment by Greenheart** [comment]
I was a bit unclear... 😄 

Yes - this is from the webpage. I meant that this this link is broken, and it probably need to be replaced with another link to the dataset.

I don't know where to find that data though.

**Comment by cheerfulstoic** [comment]
The data is linked to from that page in various formats.  We used the "I Excel-fil" link, but people might want to see the other two

**Comment by Greenheart** [comment]
That makes sense.

The problem is that I only get a HTTP 404 from that URL though. Seems like they have moved the data.

**Comment by cheerfulstoic** [comment]
😕  I'm sorry, I'm confused.  Which URL gives a 404?  When I click on any of the links under "Presentationer" they all work for me...

**Comment by Greenheart** [comment]
http://extra.lansstyrelsen.se/rus/Sv/statistik-och-data/nationell-emissionsdatabas/Pages/default.aspx

@cheerfulstoic this url gives "Not Found"

**Comment by cheerfulstoic** [comment]
Ok, that's super weird.  It works fine for me.  Maybe try another computer and/or another location with a different ISP?  Maybe they're blocking certain addresses...

**Comment by Greenheart** [comment]
Hmm, yeah that's very strange :P

**Comment by systimotic** [comment]
Link also works fine for me, but not when I try to access it through HTTPS.
@Greenheart Maybe something is forcing it to HTTPS for you?

**Comment by Greenheart** [comment]
@systimotic Thanks, you're right :smile: Apparently they don't accept HTTPS (which I'm enforcing for all web traffic).
